services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: 'YourStrong!Passw0rd'
      ACCEPT_EULA: 'Y'
    ports:
      - '1433:1433'
    volumes:
      - sqlserverdata:/var/opt/mssql

    networks:
      - app-network
      
  backend:
    build:
      context: .
      dockerfile: ./back/Dockerfile
    container_name: backend
    command: sh -c "npm run migration:run && npm run start:prod"
    env_file:
      - ./back/.env
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: frontend
    env_file:
      - ./frontend/.env
    ports:
      - '5173:5173'
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  sqlserverdata:

networks:
  app-network:
    driver: bridge