apiVersion: v1
kind: Pod
metadata:
  name: labtrans-pod
spec:
  containers:
    - name: labtrans-db-1
      image: mcr.microsoft.com/mssql/server:2022-latest
      args: ["/opt/mssql/bin/sqlservr"]
      env:
        - name: MSSQL_SA_PASSWORD
          value: YourStrong!Passw0rd
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: "Developer"
        - name: DB_NAME
          value: "master"
      ports:
        - containerPort: 1433
      volumeMounts:
        - mountPath: /var/opt/mssql
          name: labtrans_sqlserverdata
    - name: backend
      image: docker.io/library/labtrans-backend:latest
      args: ["sh", "-c", "npm run start:prod"]
      env:
        - name: DB_USERNAME
          value: sa
        - name: DB_PASSWORD
          value: YourStrong!Passw0rd
        - name: HOST
          value: 0.0.0.0
        - name: PORT
          value: "3000"
        - name: DB_HOST
          value: labtrans-db-1
        - name: DB_DATABASE
          value: master
        - name: DB_PORT
          value: "1433"
        - name: JWT_SECRET_KEY
          value: secret
      ports:
        - containerPort: 3000
          hostPort: 3000
    - name: frontend
      image: docker.io/library/labtrans-frontend:latest
      args: ["serve", "-s", ".", "-l", "5173"]
      env:
        - name: VITE_BACKEND_BASEURL
          value: http://backend:3000/
      ports:
        - containerPort: 5173
          hostPort: 5173
  volumes:
    - name: labtrans_sqlserverdata
      persistentVolumeClaim:
        claimName: labtrans_sqlserverdata-pvc
